name: sonarqube

services:

  sonarqube-db:
    image: postgres:16
    container_name: sonarqube-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${SONAR_DB_USER}
      - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
      - POSTGRES_DB=${SONAR_DB_NAME}
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - sonarqube-db
    environment:
      - SONAR_JDBC_URL=${SONAR_JDBC_URL}
      - SONAR_JDBC_USERNAME=${SONAR_DB_USER}
      - SONAR_JDBC_PASSWORD=${SONAR_DB_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_db_data:
    name: safe-zone_sonarqube_db_data
  sonarqube_data:
    name: safe-zone_sonarqube_data
  sonarqube_logs:
    name: safe-zone_sonarqube_logs
  sonarqube_extensions:
    name: safe-zone_sonarqube_extensions

networks:
  default:
    name: sonarqube-network
