server:
  port: 8443
  tomcat:
    max-swallow-size: 15MB
    max-http-form-post-size: 15MB
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: gateway

jwt:
  secret: ${JWT_SECRET:HesF/ooJT4A3JuvxFrSoxEflVK9LOHIsMp1LiMAc2/0=}

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health