server:
  port: 8082

spring:
  application:
    name: product-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/products_db}

eureka:
  client: 
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      mediaService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3